
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AMBOS FLOAT IMPAR INT LIXO PAR SEQ WORDEntry : FLOAT ',' FLOAT ',' INT ',' WORD ',' RUAS ',' WORD ',' WORD ',' INT ',' INT ',' INTRUAS : INT ':' WORD '(' PAR LIXO ':' WORD '-' WORD ')'RUAS : INT ':' WORD '(' IMPAR LIXO ':' WORD '-' WORD ')'RUAS : INT ':' WORD '(' AMBOS LIXO ':' WORD '-' WORD ')'RUAS : INT ':' WORD ',' WORDRUAS : INT ':' WORD ',' INTRUAS : INT ':' WORD ',' SEQRUAS : INT ':' WORD ',' INT WORD"
    
_lr_action_items = {'FLOAT':([0,3,],[2,4,]),'$end':([1,50,],[0,-1,]),',':([2,4,6,8,11,14,15,22,23,24,25,29,34,42,47,48,49,],[3,5,7,9,13,17,18,-6,-5,-7,30,-8,38,46,-2,-3,-4,]),'INT':([5,9,17,30,38,46,],[6,10,22,34,42,50,]),'WORD':([7,12,13,17,18,22,31,32,33,39,40,41,],[8,14,15,23,25,29,35,36,37,43,44,45,]),':':([10,26,27,28,],[12,31,32,33,]),'(':([14,],[16,]),'PAR':([16,],[19,]),'IMPAR':([16,],[20,]),'AMBOS':([16,],[21,]),'SEQ':([17,],[24,]),'LIXO':([19,20,21,],[26,27,28,]),'-':([35,36,37,],[39,40,41,]),')':([43,44,45,],[47,48,49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Entry':([0,],[1,]),'RUAS':([9,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Entry","S'",1,None,None,None),
  ('Entry -> FLOAT , FLOAT , INT , WORD , RUAS , WORD , WORD , INT , INT , INT','Entry',19,'p_Entry','dataset_yacc.py',8),
  ('RUAS -> INT : WORD ( PAR LIXO : WORD - WORD )','RUAS',11,'p_RUAS_Par','dataset_yacc.py',14),
  ('RUAS -> INT : WORD ( IMPAR LIXO : WORD - WORD )','RUAS',11,'p_RUAS_Impar','dataset_yacc.py',19),
  ('RUAS -> INT : WORD ( AMBOS LIXO : WORD - WORD )','RUAS',11,'p_RUAS_Ambos','dataset_yacc.py',24),
  ('RUAS -> INT : WORD , WORD','RUAS',5,'p_RUAS_rua_rua','dataset_yacc.py',29),
  ('RUAS -> INT : WORD , INT','RUAS',5,'p_RUAS_rua_int','dataset_yacc.py',34),
  ('RUAS -> INT : WORD , SEQ','RUAS',5,'p_RUAS_rua_seq','dataset_yacc.py',39),
  ('RUAS -> INT : WORD , INT WORD','RUAS',6,'p_RUAS_rua_INT_WORD','dataset_yacc.py',43),
]
